{
    "text-color": null,
    "background-color": "#211F20",
    "line-number-color": "#CECECE",
    "line-number-background-color": null,
    "text-styles": {
        "Normal": {
            "text-color": "#FDFCFC"
        },
        "Other": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Attribute": {
            "text-color": "#FF7276",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "SpecialString": {
            "text-color": "#3AD531",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Annotation": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Function": {
            "text-color": "#00BAE4",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "String": {
            "text-color": "#3AD531",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "ControlFlow": {
            "text-color": "#FFE900",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Operator": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Error": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "BaseN": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Alert": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Variable": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "BuiltIn": {
            "text-color": null,
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Extension": {
            "text-color": null,
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Preprocessor": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Information": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "VerbatimString": {
            "text-color": "#3AD531",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Warning": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": true,
            "underline": false
        },
        "Documentation": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": true,
            "underline": false
        },
        "Import": {
            "text-color": "#FF7276",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Char": {
            "text-color": "#3AD531",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "DataType": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Float": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Comment": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "CommentVar": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": true,
            "underline": false
        },
        "Constant": {
            "text-color": "#FFE900",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "SpecialChar": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "DecVal": {
            "text-color": "#FFAA4D",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "RegionMarker": {
            "text-color": "#00BAE4",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
        "Keyword": {
            "text-color": "#FDFCFC",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        }
    }
}